services:
  turbo:
    image: oven/bun:1.2.2
    restart: unless-stopped
    container_name: rappa-turbo
    command: "bun dev"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
      - "4000:4000"
